### Get JWT token
POST http://localhost:8080/clinics/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=rafael.pereira&password=1234

### Who am I?
GET http://localhost:8080/clinics/api/auth/user
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw


#Administrators
### GET the list of administrators
GET http://localhost:8080/clinics/api/administrators
Accept: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

### GET one administrator
GET http://localhost:8080/clinics/api/administrators/rafael.pereira
Accept: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

### Create new administrator
POST http://localhost:8080/clinics/api/administrators
Content-Type: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

{
  "username": "carlos.costa",
  "email": "2191212@my.ipleiria.pt",
  "password": "1234",
  "name": "Carlos Costa",
  "gender": "Male"
}

### Update administrator
PUT http://localhost:8080/clinics/api/administrators/carlos.costa
Content-Type: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

{
  "username": "carlos.costa",
  "email": "2191213@my.ipleiria.pt",
  "password": "1234",
  "name": "Carlos Costa",
  "gender": "Male"
}

### DELETE administrator
DELETE http://localhost:8080/clinics/api/administrators/carlos.costa
Accept: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

#Patients
### GET the list of patients
GET http://localhost:8080/clinics/api/patients
Accept: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

### GET one patient
GET http://localhost:8080/clinics/api/administrators/deniel.carreira
Accept: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

### Create new patient
POST http://localhost:8080/clinics/api/patients
Content-Type: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

{
  "username": "fabio.gaspar",
  "email": "2197643@my.ipleiria.pt",
  "password": "1234",
  "name": "Fábio Gaspar",
  "gender": "Male",
  "healthNo": 154457889,
  "created_byUsername": "bruna.leitao"
}

### Update administrator
PUT http://localhost:8080/clinics/api/patients/fabio.gaspar
Content-Type: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw

{
  "username": "fabio.gaspar",
  "email": "2197643@my.ipleiria.pt",
  "password": "1234",
  "name": "Fábio Gaspar",
  "gender": "Male",
  "healthNo": 154457889,
  "created_byUsername": "bruna.leitao"
}

### DELETE patient
DELETE http://localhost:8080/clinics/api/patients/fabio.gaspar
Accept: application/json
//Authorization: Bearer eyJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJnb25jYXNfcGFjaGVjbyIsImlzcyI6InF1aWNrc3RhcnQtand0LWlzc3VlciIsImF1ZCI6Imp3dC1hdWRpZW5jZSIsImdyb3VwcyI6WyJBZG1pbmlzdHJhdG9yIl0sImV4cCI6MTYzNjA1ODUyMH0.Hd75TQNlJDRYxq5W1agBkrmbVmDC89IzGBAmmMPBkyQoNMWs8y0GfgRMzaa0ZmEfgss8QI2m6LQVBRjAUuepXIhvtGXQt2Qwr7POQe7ymZ2Wcl2bWPIfmVFxdZ7phLdMyksxpog0JEBHE5JB5xVtgVTiT2o1fFz7FsROYiUtX8bv3LnUGh3ahNHpTknBn5WCrjvA0IucA_2AZVevCndF26fuJkeI68FTOQQKgNPznM1E887oEchbKTbTYybaNVntyTOpvmCbAF4RmV8iSQcP7En6d98AtCCI5yswzIFQYnSNIXVY9vonDR0lzBfHhyVTiaFC3nWhbG0hjz3qdXRYiw
