package pt.ipleiria.estg.dei.ei.dae.clinics.ejbs;

import pt.ipleiria.estg.dei.ei.dae.clinics.entities.Biometric_Data_Type;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Stateless
public class BiometricDataTypeBean {

    @PersistenceContext
    private EntityManager entityManager;

    /***
     *
     * @param name of the Biometric Data Type ("Temperatura Corporal")
     * @param min value acepted in input (30)
     * @param max value acepted in input (45)
     * @param measurement_unit (ºC Graus)
     * @return @Id generated by autoincrement
     */
    public long create(String name, int min, int max, String measurement_unit){

        Biometric_Data_Type biometricDataType = new Biometric_Data_Type(name, min, max, measurement_unit);
        entityManager.persist(biometricDataType);
        entityManager.flush();
        return biometricDataType.getId();

    }
}
