package pt.ipleiria.estg.dei.ei.dae.clinics.ejbs;

import pt.ipleiria.estg.dei.ei.dae.clinics.entities.BiometricDataType;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Stateless
public class BiometricDataTypeBean {

    @PersistenceContext
    private EntityManager entityManager;

    /***
     * Creating Biometric Data Type
     * @param name of the Biometric Data Type ("Temperatura Corporal")
     * @param min value acepted in input (30)
     * @param max value acepted in input (45)
     * @param measurement_unit (ºC Graus)
     * @return @Id generated by autoincrement
     */
    public long create(String name, int min, int max, String measurement_unit){

        BiometricDataType newBiometricDataType = new BiometricDataType(name, min, max, measurement_unit);
        entityManager.persist(newBiometricDataType);
        entityManager.flush();
        return newBiometricDataType.getId();

    }

    public BiometricDataType delete(long id) {
        entityManager.remove(entityManager.find(BiometricDataType.class,id));
        return entityManager.find(BiometricDataType.class,id);
    }
}
