package pt.ipleiria.estg.dei.ei.dae.clinics.ejbs;

import pt.ipleiria.estg.dei.ei.dae.clinics.entities.Biometric_Data_Issue;
import pt.ipleiria.estg.dei.ei.dae.clinics.entities.Biometric_Data_Type;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

@Stateless
public class BiometricDataIssueBean {
    @PersistenceContext
    private EntityManager entityManager;

    /***
     *
     * @param name of the Biometric Data Issue ("Febre")
     * @param min value to be with this Issue (38)
     * @param max value to be with this Issue (45)
     * @param biometric_data_type PK of Biometric_Data_Type (1:"Temperatura Corporal")
     * @return @Id generated by autoincrement
     *         -1 if not found Biometric_Data_Type
     *         -2 min or max out of bouds for limits in Biometric_Data_Type
     */
    public long create(String name, int min, int max, long biometric_data_type){
        Biometric_Data_Type biometricDataType = entityManager.find(Biometric_Data_Type.class, biometric_data_type);
        if (biometricDataType != null){

            if (min < biometricDataType.getMin() || max > biometricDataType.getMax())
                return -2; //min or max out of bouds for limits in Biometric_Data_Type

            Biometric_Data_Issue biometricDataIssue = new Biometric_Data_Issue(name, min, max, biometricDataType);
            entityManager.persist(biometricDataIssue);
            entityManager.flush();
            return biometricDataIssue.getId();
        }
        return -1; //Not found Biometric_Data_Type with this id
    }
}
