package pt.ipleiria.estg.dei.ei.dae.clinics.ejbs;

import pt.ipleiria.estg.dei.ei.dae.clinics.entities.BiometricDataIssue;
import pt.ipleiria.estg.dei.ei.dae.clinics.entities.Doctor;
import pt.ipleiria.estg.dei.ei.dae.clinics.entities.Prescription;

import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import java.text.ParseException;
import java.util.ArrayList;

@Stateless
public class PrescriptionBean {
    @PersistenceContext
    private EntityManager entityManager;

    /***
     * Creating a Prescription by a Doctor given some Biometric Data Issues
     * @param doctor_username Doctor Username that is creating the current Prescription
     * @param start_date that Prescription is starting
     * @param end_date that Prescription is ending
     * @param notes given by Doctor, the content of Prescription
     * @param bio_data_issues_ids @Id's of Biometric Data Issues that this Prescription will affect
     * @return @Id generated by autoincrement
     *         -1 if Not a found Doctor with this username
     *         -2 if Not found Biometric Data Issue with this id (bio_data_issues_id)
     */
    public long create(String doctor_username, String start_date, String end_date, String notes, long ...bio_data_issues_ids) throws ParseException {

        Doctor doctor = entityManager.find(Doctor.class, doctor_username);
        if (doctor != null) {
            ArrayList<BiometricDataIssue> biometricDataIssues = new ArrayList<>();
            for (long bio_data_issues_id : bio_data_issues_ids) {
                BiometricDataIssue biometricDataIssue = entityManager.find(BiometricDataIssue.class, bio_data_issues_id);
                if (biometricDataIssue != null) {
                    biometricDataIssues.add(biometricDataIssue);
                    continue;
                }
                return -2; //Not found Biometric Data Issue with this id (bio_data_issues_id)
            }
            Prescription prescription = new Prescription(doctor,start_date,end_date,notes,biometricDataIssues);
            entityManager.persist(prescription);

            for (BiometricDataIssue biometricDataIssue: biometricDataIssues) {
                biometricDataIssue.addPrescription(prescription);
            }

            entityManager.flush();
            return prescription.getId();

        }
        return -1; //Not found Doctor with this username
    }

    public Prescription delete(long id) {
        entityManager.remove(entityManager.find(Prescription.class,id));
        return entityManager.find(Prescription.class,id);
    }

}
